// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {postgres} from '../models';
import {main} from '../models';

export function GetAutostartEnabled():Promise<boolean>;

export function GetConfigFiles(arg1:string):Promise<postgres.ConfigFiles>;

export function GetLogs(arg1:string):Promise<string>;

export function InitDataDir(arg1:string):Promise<void>;

export function Install(arg1:string):Promise<void>;

export function InstallExtension(arg1:string,arg2:string):Promise<void>;

export function ListAvailable():Promise<Array<postgres.Version>>;

export function ListExtensions(arg1:string):Promise<Array<postgres.Extension>>;

export function ListInstalled():Promise<Array<main.VersionState>>;

export function OpenPsql(arg1:string):Promise<void>;

export function Quit():Promise<void>;

export function RevealConfigFile(arg1:string):Promise<void>;

export function SetAutostartEnabled(arg1:boolean):Promise<void>;

export function StartServer(arg1:string):Promise<void>;

export function StopServer(arg1:string):Promise<void>;

export function Uninstall(arg1:string):Promise<void>;

export function UninstallExtension(arg1:string,arg2:string):Promise<void>;

export function Use(arg1:string):Promise<void>;

export function Version():Promise<string>;
