// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAutostartEnabled() {
  return window['go']['main']['App']['GetAutostartEnabled']();
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function InitDataDir(arg1) {
  return window['go']['main']['App']['InitDataDir'](arg1);
}

export function Install(arg1) {
  return window['go']['main']['App']['Install'](arg1);
}

export function InstallExtension(arg1, arg2) {
  return window['go']['main']['App']['InstallExtension'](arg1, arg2);
}

export function ListAvailable() {
  return window['go']['main']['App']['ListAvailable']();
}

export function ListExtensions(arg1) {
  return window['go']['main']['App']['ListExtensions'](arg1);
}

export function ListInstalled() {
  return window['go']['main']['App']['ListInstalled']();
}

export function OpenPsql(arg1) {
  return window['go']['main']['App']['OpenPsql'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SetAutostartEnabled(arg1) {
  return window['go']['main']['App']['SetAutostartEnabled'](arg1);
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopServer(arg1) {
  return window['go']['main']['App']['StopServer'](arg1);
}

export function Uninstall(arg1) {
  return window['go']['main']['App']['Uninstall'](arg1);
}

export function UninstallExtension(arg1, arg2) {
  return window['go']['main']['App']['UninstallExtension'](arg1, arg2);
}

export function Use(arg1) {
  return window['go']['main']['App']['Use'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
